# Generated by Django 5.0.4 on 2024-05-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
